### ISSUE TITLE
Add `noindex` meta tag

### ISSUE THREAD

**Issue by kidonng** [stefanbuck/live-demo#2]
Search engines are indexing duplicate GitHub pages like https://octolinker-demo.now.sh/zeit/now-builders/pull/946.
We should add a `<meta name="robots" content="noindex">` tag to the `<head>`. (https://support.google.com/webmasters/answer/93710)

`robots.txt` with `Disallow: /` would also do.

**Comment by stefanbuck** [comment]
Ohh I missed the notification for this issue. Good point. Will work on it.

**Comment by stefanbuck** [comment]
I added the metatag three months ago already 😆 https://github.com/OctoLinker/live-demo/blob/b51803388a7734f898594f53b21e53eaa8faca1b/index.js#L44
